<?php

return array (
  'meta_title' => 'Erotische & Tantra Massage Palma | Erotisches Spa Mallorca - Tantric Luxe',
  'meta_description' => 'Vollständiger Katalog erotischer Massage Mallorca: Tantra Massage, Körper an Körper Palma, Paarmassage und 4-Händige Massage. Erotisches Spa Mallorca mit sofortiger Buchung.',
  'meta_keywords' => 'erotische massage mallorca, tantra massage mallorca, erotische massage palma, körper an körper massage palma, paarmassage mallorca, erotisches spa mallorca, tantra masseurin palma',
  'pre_title' => 'WIR BIETEN ERLEBNISSE',
  'title' => 'EROTISCHE SERVICES',
  'subtitle' => 'EXKLUSIVITÄT UND PRIVATSPHÄRE',
  'description' => 'Entdecken Sie unseren Katalog erotischer Massage Mallorca und Tantra Massage Palma: sensorische Erlebnisse für Vergnügen, Entspannung und Verbindung in unserem erotischen Spa Mallorca.',
  'packages_pre_title' => 'SPEZIALPAKETE',
  'packages_title' => 'EXKLUSIVE ANGEBOTE',
  'faq_pre_title' => 'HÄUFIGE FRAGEN',
  'faq_title' => 'ALLES WAS SIE WISSEN MÜSSEN',
  'reserve_button' => 'BUCHEN',
  'see_more_button' => 'MEHR SEHEN',
  'modal_includes' => 'BEINHALTET:',
  'modal_description' => 'VOLLSTÄNDIGE BESCHREIBUNG:',
  'modal_reserve_button' => 'JETZT BUCHEN',
  'modal_more_info_button' => 'MEHR INFORMATIONEN',
  'services' =>
  array (
    0 => array ( 'id' => 2, 'slug' => 'koerper-an-koerper-massage', 'title' => 'KÖRPER AN KÖRPER MASSAGE', 'duration' => '30-60 min', 'price' => 'Ab €80', 'description' => 'Körper an Körper Massage Palma mit Haut-an-Haut-Kontakt und einhüllenden Bewegungen. Eines der meistgefragten erotischen Massage-Erlebnisse Mallorca für tiefe Sinnlichkeit und Wohlbefinden.', 'meta_title' => 'Körper an Körper Massage Palma | Erotische Massage Mallorca', 'meta_description' => 'Körper an Körper Massage Palma bei Tantric Luxe. Intimer Hautkontakt, Premium-Öle und Tantra Masseurin Palma. Ab 80€. Buchen Sie in unserem erotischen Spa Mallorca.', 'meta_keywords' => 'körper an körper massage palma, erotische massage mallorca, erotische massage palma, tantra massage mallorca, erotisches spa mallorca', 'features' => array ( 0 => 'Haut-an-Haut-Kontakt', 1 => 'Sanfte einhüllende Bewegungen', 2 => 'Tiefe sensorische Verbindung', 3 => 'Entspannung und Wohlbefinden' ), 'fullDescription' => 'Unsere Körper an Körper Massage Palma ist ein intimes Erlebnis, bei dem die Tantra Masseurin mit fließenden Bewegungen und warmen Ölen über Ihren Körper gleitet und eine einzigartige sensorische Verbindung schafft. Unter den meistgebuchten erotischen Massagen Mallorca vereint sie Sinnlichkeit, Entspannung und Vergnügen in Palma de Mallorca. Optionen: 30 Min – 80€ | 45 Min – 120€ | 60 Min – 150€.', 'image' => '/images/sensual_premium.webp' ),
    1 => array ( 'id' => 3, 'slug' => 'erotisches-dusch-erlebnis', 'title' => 'EROTISCHES DUSCH-ERLEBNIS', 'duration' => '60 min', 'price' => '€200', 'description' => 'Erotisches Ritual unter Wasser in unserem erotischen Spa Mallorca. Streicheleinheiten, Wärme und Körpernähe für ein unvergessliches erotisches Massage-Erlebnis Palma.', 'meta_title' => 'Erotisches Dusch-Erlebnis Palma | Erotisches Spa Mallorca', 'meta_description' => 'Erotisches Dusch-Erlebnis in Palma de Mallorca. Sensorische Massage unter Wasser mit Tantra Masseurin. 60 Min – 200€. Buchen bei Tantric Luxe.', 'meta_keywords' => 'erotisches dusch erlebnis palma, erotische massage palma, erotische massage mallorca, erotisches spa mallorca, tantra massage mallorca', 'features' => array ( 0 => 'Warme Atmosphäre unter Wasser', 1 => 'Nahkontakt und sensorische Berührung', 2 => 'Sanfte einhüllende Streicheleinheiten', 3 => 'Atmosphäre von Vergnügen und Verbindung' ), 'fullDescription' => 'Das erotische Dusch-Erlebnis erhebt erotische Massage Palma zu einem aquatischen Ritual aus Vergnügen und Verbindung. In unserem erotischen Spa Mallorca wecken warmes Wasser, bewusste Berührungen und Körpernähe die Sinne und schaffen einen intimen Moment unter den exklusivsten erotischen Massagen Mallorca.', 'image' => '/images/exotic_paradise.webp' ),
    2 => array ( 'id' => 4, 'slug' => 'prostatamassage', 'title' => 'PROSTATAMASSAGE', 'duration' => '60 min', 'price' => '€200', 'description' => 'Professionelle Prostatamassage in Palma mit präzisen Techniken, maximaler Hygiene und Privatsphäre. Männliches Wohlbefinden in unserem erotischen Massage-Katalog Mallorca.', 'meta_title' => 'Prostatamassage Palma | Erotische Massage Mallorca', 'meta_description' => 'Prostatamassage in Palma de Mallorca. Experten-Techniken, intime Atmosphäre und totale Diskretion in unserem erotischen Spa Mallorca. 60 Min – 200€.', 'meta_keywords' => 'prostatamassage palma, erotische massage palma, erotische massage mallorca, tantra massage mallorca, erotisches spa mallorca', 'features' => array ( 0 => 'Spezialisierte Techniken', 1 => 'Intime und entspannende Atmosphäre', 2 => 'Maximale Privatsphäre', 3 => 'Zertifizierte Fachkräfte' ), 'fullDescription' => 'Prostatamassage in Palma de Mallorca verbindet präzise Stimulation, Respekt und absolute Vertraulichkeit. Als Teil unserer erotischen Massage Mallorca ist diese Sitzung darauf ausgelegt, Spannungen zu lösen, männliches Vergnügen zu intensivieren und ein intimes Erlebnis nach höchsten Standards unseres erotischen Spa Mallorca zu bieten.', 'image' => '/images/sensual_premium.webp' ),
    3 => array ( 'id' => 5, 'slug' => 'privater-striptease', 'title' => 'PRIVATER STRIPTEASE', 'duration' => '60 min', 'price' => '€250', 'description' => 'Private Striptease-Show in Palma mit Eleganz und Sinnlichkeit. Perfekte Ergänzung vor erotischer Massage Palma oder exklusivem Tantra-Ritual.', 'meta_title' => 'Privater Striptease Palma | Erotische Massage Mallorca', 'meta_description' => 'Privater Striptease in Palma de Mallorca. Exklusive erotische Show im erotischen Spa Mallorca. 60 Min – 250€. Jetzt buchen.', 'meta_keywords' => 'privater striptease palma, erotische massage palma, erotische massage mallorca, erotisches spa mallorca, tantra massage mallorca', 'features' => array ( 0 => 'Exklusive private Show', 1 => 'Sinnlicher und eleganter Tanz', 2 => 'Blickspiele und Attitüde', 3 => 'Intime und verführerische Atmosphäre' ), 'fullDescription' => 'Privater Striptease in Palma de Mallorca öffnet die Tür zu einem visuellen und erotischen Erlebnis auf höchstem Niveau. Jede Bewegung weckt Fantasie und bereitet den Körper auf eine anschließende Tantra Massage oder erotische Massage Palma in unserem exklusiven erotischen Spa Mallorca vor.', 'image' => '/images/exotic_paradise.webp' ),
    4 => array ( 'id' => 6, 'slug' => 'premium-erlebnis', 'title' => 'PREMIUM-ERLEBNIS', 'duration' => '70 min', 'price' => '€300', 'description' => 'Das vollständigste erotische Massage-Erlebnis Mallorca: Striptease, intime Dusche, Körper an Körper PLUS Massage und Champagner in unserem erotischen Spa Mallorca.', 'meta_title' => 'Premium-Erlebnis Palma | Erotisches Spa Mallorca', 'meta_description' => 'Premium-Erlebnis in Palma: Striptease, erotische Dusche, Körper an Körper Massage und Champagner. Das exklusivste Tantra Massage Mallorca Ritual. Jetzt buchen.', 'meta_keywords' => 'premium erlebnis palma, erotische massage mallorca, körper an körper massage palma, erotisches spa mallorca, tantra massage mallorca', 'features' => array ( 0 => 'Privater Striptease', 1 => 'Intimes Dusch-Erlebnis', 2 => 'Körper an Körper PLUS Massage', 3 => 'Glas Champagner inklusive' ), 'fullDescription' => 'Das Premium-Erlebnis vereint das Beste aus erotischer Massage Palma und Tantra Massage Mallorca in einem 70-minütigen Ritual. Privater Striptease, sensorische Dusche, intensivierte Körper an Körper Massage Palma und Champagner: das definitive Angebot unseres erotischen Spa Mallorca für maximalen sensorischen Luxus.', 'image' => '/images/sensual_premium.webp' ),
    5 => array ( 'id' => 7, 'slug' => '4-haendige-massage', 'title' => '4-HÄNDIGE MASSAGE', 'duration' => '60 min', 'price' => '€300', 'description' => '4-Händige Massage Palma mit zwei synchronisierten Tantra Masseurinnen. Doppeltes Vergnügen, totale Entspannung und eine Perle der erotischen Massage Mallorca.', 'meta_title' => '4-Händige Massage Palma | Erotische Massage Mallorca', 'meta_description' => '4-Händige Massage Palma mit zwei erfahrenen Tantra Masseurinnen. Perfekte Synchronisation im erotischen Spa Mallorca. 60 Min – 300€.', 'meta_keywords' => '4 händige massage palma, erotische massage mallorca, tantra massage mallorca, tantra masseurin palma, erotisches spa mallorca', 'features' => array ( 0 => 'Zwei synchronisierte Masseurinnen', 1 => 'Gleichzeitige Berührungen', 2 => 'Fließende einhüllende Bewegungen', 3 => 'Tiefes Vergnügen und totale Entspannung' ), 'fullDescription' => '4-Händige Massage Palma vervielfacht die Empfindungen mit zwei Tantra Masseurinnen, die im Einklang über Ihren Körper gleiten. Unter den intensivsten erotischen Massagen Mallorca verbindet sie Erregung, tiefe Entspannung und einen hypnotischen Rhythmus, den nur ein erstklassiges erotisches Spa Mallorca in Palma de Mallorca bieten kann.', 'image' => '/images/exotic_paradise.webp' ),
    6 => array ( 'id' => 8, 'slug' => 'paarmassage', 'title' => 'PAARMASSAGE', 'duration' => '60 min', 'price' => '€280', 'description' => 'Paarmassage Mallorca zum Teilen von Vergnügen und Verbindung. Tantrisches oder erotisches Ritual mit einer oder zwei Masseurinnen in intimer, exklusiver Atmosphäre.', 'meta_title' => 'Paarmassage Mallorca | Erotische Massage Palma', 'meta_description' => 'Paarmassage Mallorca bei Tantric Luxe. Tantra oder erotische Massage zu zweit im erotischen Spa Mallorca. 60 Min – 280€. Jetzt buchen.', 'meta_keywords' => 'paarmassage mallorca, erotische massage palma, erotische massage mallorca, tantra massage mallorca, erotisches spa mallorca', 'features' => array ( 0 => 'Option 1 oder 2 Masseurinnen', 1 => 'Sanfte einhüllende Berührungen', 2 => 'Sinnliche und entspannende Atmosphäre', 3 => 'Tiefe Paarverbindung' ), 'fullDescription' => 'Paarmassage Mallorca ist für zwei Personen konzipiert, die Sinnlichkeit, Ruhe und Erregung im selben Ritual teilen. Mit einer erfahrenen Tantra Masseurin Palma in Paardynamik stärkt dieses erotische Massage Palma Erlebnis die Verbindung und steigert gemeinsames Vergnügen in unserem erotischen Spa Mallorca.', 'image' => '/images/couples_harmony.webp' ),
  ),
  'packages' => array ( 0 => array ( 'title' => 'TREUERABATT', 'day' => 'JEDEN DONNERSTAG', 'description' => 'Treue Kunden verdienen eine Belohnung. Wenn Sie unsere Massagen schon kennen, erhalten Sie diesen Donnerstag einen <span class=\'text-amber-400 font-semibold\'>20€ Rabatt-Gutschein</span> auf Ihre Sitzung.', 'buttonText' => 'DONNERSTAG BUCHEN' ), 1 => array ( 'title' => 'GETEILTES VERGNÜGEN', 'day' => 'JEDEN SAMSTAG', 'description' => 'Jeden Samstag in Begleitung... Teilen Sie den Moment mit einem Freund und genießen Sie beide <span class=\'text-amber-400 font-semibold\'>10% Rabatt</span> auf Ihr Erlebnis.', 'buttonText' => 'SAMSTAG BUCHEN' ), 2 => array ( 'title' => 'SONNTAGE ZUM GENIESSEN', 'day' => 'JEDEN SONNTAG', 'description' => 'Wählen Sie eine Vier-Hand-Massage zum exklusiven Preis. Mehr Hände... mehr Vergnügen. Ein intensiviertes Erlebnis für alle, die tiefer eintauchen möchten.', 'buttonText' => 'SONNTAG BUCHEN' ) ),
  'faqs' => array ( 0 => array ( 'question' => 'Was beinhalten die Services?', 'answer' => 'Alle Services beinhalten persönliche Beratung, klimatisierte Umgebung, Ambient-Musik, Premium-Öle und warme Handtücher. Premium-Services umfassen zusätzliche Annehmlichkeiten wie Champagner und private Jacuzzis.' ), 1 => array ( 'question' => 'Wie kann ich buchen?', 'answer' => 'Buchen Sie per WhatsApp, Online-Formular oder telefonisch. Wir empfehlen mindestens 24 Stunden im Voraus. Für Premium-Services sind 48 Stunden erforderlich.' ), 2 => array ( 'question' => 'Welche Privatsphäre-Maßnahmen gibt es?', 'answer' => 'Wir garantieren absolute Diskretion. Private Eingänge, keine Weitergabe von Kundendaten und Vertraulichkeitsvereinbarungen für das gesamte Personal.' ) ),
);
